services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports: ["5000:5000"]
    environment:
      - PORT=5000
      - CORS_ORIGIN=http://localhost:3000
    networks: [appnet]

  web:
    build:
      context: ./frontend
    ports: [ "8888:80" ]
    depends_on: [ api ]
    networks: [ appnet ]

networks:
  appnet:
