version: "3.8"
services:
  api:
    image: plunev/notes-api:latest
    environment:
      - PORT=5000
      - CORS_ORIGIN=http://${PUBLIC_HOST:-localhost}
    networks: [appnet]

  web:
    image: plunev/notes-web:latest
    ports:
      - "80:80"
    depends_on: [api]
    networks: [appnet]

networks:
  appnet:
