name: CI — Build & Push images

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
    outputs:
      short_sha:
        description: "Short SHA of the built commit"
        value: ${{ jobs.build-and-push.outputs.short_sha }}
        
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Short SHA
        id: v
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/notes-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/notes-api:${{ steps.v.outputs.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/notes-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/notes-api:buildcache,mode=max

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/notes-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/notes-web:${{ steps.v.outputs.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/notes-web:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/notes-web:buildcache,mode=max

      - name: Upload deploy bundle
        uses: actions/upload-artifact@v4
        with:
          name: deploy-bundle
          path: deploy/docker-compose.yml
